# Generated by Django 3.1.3 on 2021-01-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro_pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=16, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=32, verbose_name='Sobrenome')),
                ('idade', models.PositiveIntegerField()),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('apelido', models.CharField(max_length=8, verbose_name='Apelido')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Cadastro_Pessoas',
            },
        ),
    ]
